// export class yeuCauBaoGiaCreateRequest {
//     id: string,
//     nhomVatId: 1,
//     donViBaoGiaId: 1,
//     donViDuocYeuCauId: 2,
//     tenNhomVatTu: Nhóm vật tư 1,
//     soDeNghi: abc,
//     tuNgay: 2021-05-31T17:00:00,
//     denNgay: 2021-06-07T17:00:00,
//     trangThai: -1,
//     quy: 1,
//     nam: 2021,
//     vanBanKemTheo: null,
//     ghiChu: test,
//     ngayYeuCau: 2021-06-15T11:12:07.7280715,
//     donViYeuCauId: 0,
//     thoiGianTao: 2021-06-15T11:12:07.8615355,
//     nguoiTaoId: 0,
//     thoiGianCapNhat: 2021-06-15T11:12:07.7281149,
//     nguoiCapNhatId: 0,
//     donViThamDinhId: 2,
//     tenDonViThamDinh: DV thẩm định 1,
//     vatTu: [
//         {
//             id: 1,
//             maVatTu: VT1,
//             tenVatTu: vật tư 1,
//             nhomVatTuId: 1,
//             tenNhomVatTu: null,
//             thongSoKyThuat: abc,
//             moTa: abc,
//             nguoiTaoId: 0,
//             thoiGianTao: 2021-06-14T16:52:52.3274072,
//             nuocSanXuatId: 1,
//             tenNuocSX: null,
//             donViTinhId: 1,
//             tenDonVi: Máy,
//             hangSanXuatId: 1,
//             tenHangSanXuat: null
//         },
//         {
//             id: 2,
//             maVatTu: VT2,
//             tenVatTu: vật tư 2,
//             nhomVatTuId: 1,
//             tenNhomVatTu: null,
//             thongSoKyThuat: abc,
//             moTa: abc,
//             nguoiTaoId: 0,
//             thoiGianTao: 2021-06-14T16:52:52.3274072,
//             nuocSanXuatId: 2,
//             tenNuocSX: null,
//             donViTinhId: 1,
//             tenDonVi: Máy,
//             hangSanXuatId: 2,
//             tenHangSanXuat: null
//         },
//         {
//             id: 1,
//             maVatTu: VT1,
//             tenVatTu: vật tư 1,
//             nhomVatTuId: 1,
//             tenNhomVatTu: null,
//             thongSoKyThuat: abc,
//             moTa: abc,
//             nguoiTaoId: 0,
//             thoiGianTao: 2021-06-15T11:12:07.7279648,
//             nuocSanXuatId: 1,
//             tenNuocSX: null,
//             donViTinhId: 1,
//             tenDonVi: Máy,
//             hangSanXuatId: 1,
//             tenHangSanXuat: null
//         },
//         {
//             id: 1,
//             maVatTu: VT1,
//             tenVatTu: vật tư 1,
//             nhomVatTuId: 1,
//             tenNhomVatTu: null,
//             thongSoKyThuat: abc,
//             moTa: abc,
//             nguoiTaoId: 0,
//             thoiGianTao: 2021-06-15T11:12:07.7279648,
//             nuocSanXuatId: 1,
//             tenNuocSX: null,
//             donViTinhId: 1,
//             tenDonVi: Máy,
//             hangSanXuatId: 1,
//             tenHangSanXuat: null
//         }
//     ],
//     baoGiaId: 0,
//     soDienThoai: 093333333,
//     email: email@gmail.com,
//     diaChi: TB1,
//     nguoiLienHe: null,
//     version: 0,
//     tenDonVi: NCC1,
//     ngayBaoGia: null
// }
// }